---
name: Dependabot auto-merge
"on": pull_request_target

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Enable auto-merge for Dependabot PRs
        uses: ./
        env:
          app_id: ${{ secrets.APP_ID }}
          app_private_key: ${{ secrets.PRIVATE_KEY }}
