---
name: Dependabot auto-merge
"on":
  pull_request_target:
    types: [opened]

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - uses: devon-mar/auto-merge-action@master
        with:
          app_id: ${{ secrets.APP_ID }}
          app_private_key: ${{ secrets.PRIVATE_KEY }}
