---
name: Dependabot auto-merge
on: pull_request_target

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Enable auto-merge for Dependabot PRs
        uses: ./
        env:
          app_id: ${{ secrets.APP_ID }}
          app_private_key: ${{ secrets.PRIVATE_KEY }}
